on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: swift test --enable-code-coverage
      - run: cp "$(swift test --show-codecov-path)" coverage.json
      - uses: codecov/codecov-action@v2
