on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: swift test --enable-code-coverage
      - run: llvm-cov export .build/debug/FxPackageTests.xctest -format lcov -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
      - uses: codecov/codecov-action@v2
