on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: swift test --enable-code-coverage
      - uses: codecov/codecov-action@v2
